### ISSUE TITLE
Harfbuzz Integration

### ISSUE THREAD

**Issue by Chashm-e-Afreen** [cycfi/elements#234]
Hi! 
Hope you're doing well. Just recently came across this wonderful GUI library. The issue at hand is that RTL languages currently do not render properly. Integrating Harfbuzz should solve the problem.

**Comment by Xeverous** [comment]
This probably belongs to [artist](https://github.com/cycfi/artist) which is planned to be the backend implementation. Artist is planned to use Skia (which has a lot of own dependencies, Harfbuzz included IIRC) which supports RTL.

**Comment by djowel** [comment]
> This probably belongs to [artist](https://github.com/cycfi/artist) which is planned to be the backend implementation. Artist is planned to use Skia (which has a lot of own dependencies, Harfbuzz included IIRC) which supports RTL.

No, this belongs here. Elements develop and main branches do not use Harfbuzz and is the reason for this issue.

Some corrections:

- Artist already uses Harfbuzz. 
- Artist already uses Skia (not planned to use)
- Harfbuzz is NOT a dependency of Skia

The correct answer: Please try the artist_port branch. It is the future of Elements.

**Comment by Chashm-e-Afreen** [comment]
Thanks a lot for the clarification. I tried the artist_port branch but the textedit example crashes when a non ASCII character is entered.

**Comment by djowel** [comment]
> Thanks a lot for the clarification. I tried the artist_port branch but the textedit example crashes when a non ASCII character is entered.

The artist_port is very new and surely needs to be tested more before it goes to develop and then master:

1. Can you repro the crash by copy/pasting the text?
2. If yes, can you share the text that you pasted?

**Comment by djowel** [comment]
@Chashm-e-Afreen , do you have an update on this? I tried pasting russian, but I do not get the crash you mentioned:
<img width="527" alt="Screen Shot 2020-10-22 at 5 46 49 AM" src="https://user-images.githubusercontent.com/568094/96790957-3082ea00-142a-11eb-8400-055f75569b49.png">

**Comment by djowel** [comment]
OK, please try the updated code (I pushed to the artist_branch). I fixed some code probably related to the issue you mentioned. I'd appreciate it if you can give it a try and stress test the example well.

**Comment by Chashm-e-Afreen** [comment]
Sorry for not being able to reply. I'll give it a test and update you soon.

**Comment by Chashm-e-Afreen** [comment]
Still no luck, entering an RTL unicode point causes the application to crash, copy pasting works but RTL fonts do not work particularly well. For LTR languages it's all good I guess.

**Comment by djowel** [comment]
> Still no luck, entering an RTL unicode point causes the application to crash, copy pasting works but RTL fonts do not work particularly well. For LTR languages it's all good I guess.

Could you give me a stack trace of the crash? Would you be willing to work with me on making this work? I'll need to figure out a way to test this myself, install RTL fonts and input methods, etc. For example, we can probably feed the input programmatically (instead of typing) and make a test out of it. I should start making tests and this can be a good start.

**Comment by Chashm-e-Afreen** [comment]
Yeah, I'll be glad to help. The segmentation fault occurs in the 

`inline std::u32string to_utf32(std::string_view s)`

function. I'll try my best to fix it.

**Comment by Chashm-e-Afreen** [comment]
Figured out where the problem is, the loop variable gets incremented twice and hence never becomes equal to the last code point. This leads to an infinite loop. The decode_utf8 automaton might be at fault here.

**Comment by djowel** [comment]
> Figured out where the problem is, the loop variable gets incremented twice and hence never becomes equal to the last character. This leads to an infinite loop. The decode_utf8 automaton might be at fault here.

Hmm... OK, can you give me an input string I can try?

In any case, I think the text element and layout engine needs a lot of work because they all assume LTR, although the harfbuzz engine itself can do RTL, and so is Skia, I assume. So this is doable, and I'd like to make it work.

**Comment by Chashm-e-Afreen** [comment]
Sure, here's a simple RTL string

حرف باز

You can get an RTL font from here

https://github.com/notofonts/NotoNastaliqUrdu/blob/master/fonts/ttf/unhinted/instance_ttf/NotoNastaliqUrdu-Regular.ttf
